coverage:
  status:
    #仅仅统计pull request
    patch:
      default:
        ## 必须满足的最低覆盖率才能被视为success
        target: 50%
        ## 最多允许覆盖率下降0.1%,才能视为success
        threshold: 0.1%
## 忽略的文件
ignore:
  - "src/main/java/com.xy.datasource.spring.boot.starter.annotation/.*"
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - "!*-dev"